version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none               

  enable:
    - bodyclose
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - noctx
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused

  settings:
    gocyclo:
      min-complexity: 15

    revive:
      rules:
        - name: exported
          severity: warning

    gosec:
      excludes:
        - G104 

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
          - bodyclose